language: c++
sudo: false

git:
  depth: 10
  submodules: false

matrix:
  include:
    - os: linux
      env: COMPILER=g++-4.9 CMAKE_BUILD_TYPE=Release
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.9
          - g++-4.9

    - os: linux
      env: COMPILER=g++-5 CMAKE_BUILD_TYPE=Release
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-5
          - g++-5

    - os: linux
      env: COMPILER=g++-6 CMAKE_BUILD_TYPE=Release
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-6
          - g++-6

    - os: linux
      env: COMPILER=g++-7 CMAKE_BUILD_TYPE=Release
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-7
          - g++-7

    - os: linux
      env: COMPILER=clang++-3.6 CMAKE_BUILD_TYPE=Release
      compiler: clang
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.6
          packages:
          - clang-3.6

    - os: linux
      env: COMPILER=clang++-3.7 CMAKE_BUILD_TYPE=Release
      compiler: clang
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.7
          packages:
          - clang-3.7

    - os: linux
      env: COMPILER=clang++-3.8 CMAKE_BUILD_TYPE=Release
      compiler: clang
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.8
          packages:
          - clang-3.8

    - os: linux
      env: COMPILER=clang++-3.9 CMAKE_BUILD_TYPE=Release
      compiler: clang
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.9
          packages:
          - clang-3.9

    - os: linux
      env: COMPILER=clang++-4.0 CMAKE_BUILD_TYPE=Release
      compiler: clang
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-4.0
          packages:
          - clang-4.0

install:
  # install a recent cmake
  - curl -O https://cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
  - tar -xf cmake-3.2.3-Linux-x86_64.tar.gz
  - rm -f cmake-3.2.3-Linux-x86_64.tar.gz
  - export PATH=${PWD}/cmake-3.2.3-Linux-x86_64/bin:${PATH}

before_script:
  - mkdir build
  - cd build
  - cmake --version
  - ${COMPILER} --version
  - CXX=${COMPILER} cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..

script:
  - make
  - make unittest
