language: c++
compiler:
  - gcc
  - clang
sudo: false
os: linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-4.9
    - g++-4.9
    - clang-3.6

install:
  - if [ "$CXX" = "g++" ] ; then export CXX="g++-4.9" CC="gcc-4.9" ; fi
  - if [ "$CXX" = "clang++" ] ; then export CXX="clang++-3.6" CC="clang-3.6" ; fi

  # install a recent cmake
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
  - tar -xf cmake-3.2.3-Linux-x86_64.tar.gz
  - rm -f cmake-3.2.3-Linux-x86_64.tar.gz
  - export PATH=${PWD}/cmake-3.2.3-Linux-x86_64/bin:${PATH}

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - ${CXX} --version
  - make
  - make unittest
